-- MySQL Script generated by MySQL Workbench
-- Tue Sep 19 20:14:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_pharmacy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_pharmacy` ;

-- -----------------------------------------------------
-- Schema db_pharmacy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pharmacy` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_pharmacy` ;

-- -----------------------------------------------------
-- Table `db_pharmacy`.`tb_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pharmacy`.`tb_category` ;

CREATE TABLE IF NOT EXISTS `db_pharmacy`.`tb_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_pharmacy`.`tb_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pharmacy`.`tb_users` ;

CREATE TABLE IF NOT EXISTS `db_pharmacy`.`tb_users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `picture` VARCHAR(5000) NULL DEFAULT NULL,
  `user` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_pharmacy`.`tb_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pharmacy`.`tb_product` ;

CREATE TABLE IF NOT EXISTS `db_pharmacy`.`tb_product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `date` DATETIME(6) NULL DEFAULT NULL,
  `text` VARCHAR(1000) NULL DEFAULT NULL,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `category_id` BIGINT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK8i0sq9mfbpsrabrm2pum9fspo` (`category_id` ASC),
  INDEX `FKrwjj68ypp5val1nvc5dd2ggqs` (`user_id` ASC),
  CONSTRAINT `FK8i0sq9mfbpsrabrm2pum9fspo`
    FOREIGN KEY (`category_id`)
    REFERENCES `db_pharmacy`.`tb_category` (`id`),
  CONSTRAINT `FKrwjj68ypp5val1nvc5dd2ggqs`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_pharmacy`.`tb_users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
